-- Lua 5.5
-- Reference: https://www.lua.org/manual/5.5/manual.html

local function parse_string(C, w)
	local i = C[2]
	local c = string.sub(C[1], i, i)
	if c == w then
		local S = i
		local o = ""
		i = i + 1
		while i <= #C[1] do
			c = string.sub(C[1], i, i)
			if c == "\\" then
				c = string.sub(C[1], i + 1, i + 1)
				if c then
					local t = {
						a = "\a",
						b = "\b",
						f = "\f",
						n = "\n",
						r = "\r",
						t = "\t",
						v = "\v",
						["\\"] = "\\",
						["'"] = "'",
						['"'] = '"',
						["0"] = "\0",
					}
					if t[c] then
						o = o .. t[c]
						i = i + 1
					else
						error("Unknown escape sequence: \\" .. c)
					end
				else
					error("Invalid escape, is at the end of the source")
				end
			elseif c == w then
				break
			else
				o = o .. c
			end
			i = i + 1
		end
		table.insert(C[3], { T = "l", t = w, i = o, span = { S, i } })
		C[2] = i + 1
		return true
	end
	return false
end

local function parse_long_bracket(C)
	local i = C[2]
	local s, e = string.find(C[1], "^%[=*%[", i)
	if not s or s >= e then
		return nil
	end
	local S, B = s, e + 1
	local a = (e - s) - 1
	s, e = string.find(C[1], "]" .. string.rep("=", a) .. "]", e, true)
	if not s or s >= e then
		error("Unclosed long Bracket")
		return nil
	end
	return { S, e }, a, string.sub(C[1], B, s - 1)
end

local function parse_long_string(C)
	local span, a, i = parse_long_bracket(C)
	if not span then
		return false
	end
	C[2] = span[2] + 1
	table.insert(C[3], { T = "l", t = a, i = i, span = span })
	return true
end

local function parse(source)
	local C = { source, 1, {} }
	local i = 1
	while i <= #source do
		local s, e, r
		repeat
			s, e = string.find(source, "^ *", i)
			if s and s <= e then
				table.insert(C[3], { T = "w", t = " ", amount = 1 + e - s, span = { s, e } })
				i = e + 1
				break
			end
			s, e = string.find(source, "^\t*", i)
			if s and s <= e then
				table.insert(C[3], { T = "w", t = "\t", amount = 1 + e - s, span = { s, e } })
				i = e + 1
				break
			end
			s, e = string.find(source, "^\n*", i)
			if s and s <= e then
				table.insert(C[3], { T = "w", t = "\n", amount = 1 + e - s, span = { s, e } })
				i = e + 1
				break
			end
			s, e, r = string.find(source, "^(%d+%.?%d*)", i)
			if s and s <= e then
				table.insert(C[3], { T = "l", t = "n", i = r, span = { s, e } })
				i = e + 1
				break
			end
			s, e, r = string.find(source, "^(0x%d+%.?%d*)", i)
			if s and s <= e then
				table.insert(C[3], { T = "l", t = "n", i = r, span = { s, e } })
				i = e + 1
				break
			end
			s, e, r = string.find(source, "^([%a_][%w_]*)", i)
			if s and s <= e then
				table.insert(C[3], { T = "i", i = r, span = { s, e } })
				i = e + 1
				break
			end
			C[2] = i
			if parse_string(C, "'") or parse_string(C, '"') or parse_long_string(C) then
				i = C[2]
				break
			end
			s, e = string.find(source, "^%-%-", i)
			if s and s < e then
				i = i + 2
				C[2] = i
				local span, a, c = parse_long_bracket(C)
				if span then
					i = span[2] + 1
					table.insert(C[3], { T = "c", a = a, i = c, span = { span[1] - 2, span[2] } })
					break
				end
				local S = s
				s = string.find(source, "\n", i, true)
				E = s or #source
				i = E + 1
				table.insert(C[3], { T = "c", i = string.sub(source, S + 2, E - 1), span = { S, E } })
				break
			end
			s, e, r = string.find(source, "^(%p)", i)
			if s and s <= e then
				table.insert(C[3], { T = "p", i = r, span = { s, e } })
				i = e + 1
				break
			end
		until true
	end

	return C[3]
end

local function tok_trim(C)
	local i = C[2]
	while i <= #C[1] do
		local t = C[1][i]
		if t.T ~= "w" and t.T ~= "c" then
			break
		end
		i = i + 1
	end
	C[2] = i
end

-- Reference: https://www.lua.org/manual/5.5/manual.html#3.1
local keywords = {
	["and"] = true,
	["break"] = true,
	["do"] = true,
	["else"] = true,
	["elseif"] = true,
	["end"] = true,
	["false"] = true,
	["for"] = true,
	["function"] = true,
	["if"] = true,
	["in"] = true,
	["local"] = true,
	["nil"] = true,
	["not"] = true,
	["or"] = true,
	["repeat"] = true,
	["return"] = true,
	["then"] = true,
	["true"] = true,
	["until"] = true,
	["while"] = true,
	["global"] = true, -- unused
	["goto"] = true, -- cannot be implemented easily inside the executor!
}

-- Reference: https://www.lua.org/manual/5.5/manual.html#3.4.8
local ast_priorities = {
	[3] = 11, -- not
	[11] = 2, -- and
	[12] = 1, -- or
	[20] = 9, -- `+`
	[21] = 9, -- `-`
	[22] = 10, -- `*`
	[23] = 10, -- `/`
	[24] = 12, -- `^`
	[25] = 5, -- `~`
	[26] = 6, -- `&` bit and
	[27] = 10, -- `%`
	[28] = 3, -- `<`
	[29] = 3, -- `>`
	[30] = 3, -- `==`
	[31] = 3, -- `~=`
	[32] = 8, -- `..`
	[33] = 10, -- `//`
	[34] = 4, -- `|` bit or
	[35] = 7, -- `<<` shl
	[36] = 7, -- `>>` shr
	[38] = 3, -- `<=`
	[39] = 3, -- `>=`
	[50] = 11, -- `-` negation
	[51] = 11, -- `#`
	[52] = 11, -- `~` logical negation
}

-- This is enough?
-- Somehow this passed all the presedence tests, that ware generated by Gemini 3 Fast
-- TODO: if needed improve this using Pratt Parsing
local function ast_expr_apply_precedence(E)
	local pt = ast_priorities[E[1]] or 0

	if E[1] > 10 and E[1] < 50 then
		local pl = ast_priorities[E[2][1]] or 0
		local pr = ast_priorities[E[3][1]] or 0

		if E[3][1] > 10 and E[3][1] < 50 then
			--[[
				(*, 2, (+, 10, 5)) ->
				(+, (*, 2, 10), 5)
			]]
			if pt > pr then
				return { E[3][1], { E[1], E[2], E[3][2], span = { 0, 0 } }, E[3][3], span = { 0, 0 } }
			end
		end

		return E
	elseif E[1] == 3 or E[1] > 49 and E[1] < 60 then
		local pr = ast_priorities[E[2][1]] or 0
		if E[2][1] > 10 and E[2][1] < 50 then
			--[[
				(#, (==, {}, 1)) ->
				(==, (#, {}), 1)
			]]
			if pt > pr then
				return { E[2][1], { E[1], E[2][2], span = { 0, 0 } }, E[2][3], span = { 0, 0 } }
			end
		end
		return E
	else
		return E
	end
end
local ast_parse_stmt
local ast_parse_path
local ast_parse_expr
local ast_parse_call
local ast_parse_table
local ast_parse_path_
local function ast_parse_expr_(C)
	local t = C[1][C[2]]
	if not t then
		return
	end
	if t.T == "i" then
		if t.i == "nil" then
			C[2] = C[2] + 1
			return { 0, span = t.span }
		elseif t.i == "false" then
			C[2] = C[2] + 1
			return { 1, span = t.span }
		elseif t.i == "true" then
			C[2] = C[2] + 1
			return { 2, span = t.span }
		elseif t.i == "not" then
			C[2] = C[2] + 1
			tok_trim(C)
			local e = ast_parse_expr(C)
			if not e then
				error("Incomplete `not` expression at: " .. t.span[1] .. "-" .. t.span[2])
			end
			return { 3, e, span = { t.span[1], e.span[2] } }
		elseif t.i == "function" then
			C[2] = C[2] + 1
			tok_trim(C)
			local k = C[1][C[2]]
			local a = {}

			if not (k.T == "p" and k.i == "(") then
				error("Function definition expects the paramenters to begin wtih `(`")
			end
			repeat
				C[2] = C[2] + 1
				tok_trim(C)
				k = C[1][C[2]]
				if not k then
					error("Expect function parameters to end with `)`")
				end
				if k.T == "p" and k.i == ")" then
					break
				elseif k.T == "p" and k.i == "." then
					k = C[1][C[2] + 1]
					if not k or k.T ~= "p" or k.i ~= "." then
						error("A unexpected `.` in function parameters")
					end
					k = C[1][C[2] + 2]
					if not k or k.T ~= "p" or k.i ~= "." then
						error("A unexpected `..` in function parameters")
					end
					C[2] = C[2] + 3
					tok_trim(C)
					k = C[1][C[2]]
				elseif k.T == "i" then
					table.insert(a, k.i)
					C[2] = C[2] + 1
					tok_trim(C)
					k = C[1][C[2]]
				else
					error("Expecting an ident for the function paramenters")
				end
				if k.T == "p" and k.i == ")" then
				elseif not (k.T == "p" and k.i == ",") then
					error("No `,` between parameters, `,` is required to separate aparameters, at token: " .. C[2])
				end
			until not k or (k.T == "p" and k.i == ")")
			if not k or not (k.T == "p" and k.i == ")") then
				error("Cannot find function parameters end, `)`")
			end

			C[2] = C[2] + 1

			local s = {}
			repeat
				tok_trim(C)
				k = C[1][C[2]]
				while k and k.T == "p" and k.i == ";" do
					C[2] = C[2] + 1
					tok_trim(C)
					k = C[1][C[2]]
				end
				if not k or k.T == "i" and k.i == "end" then
					break
				end
				local r = ast_parse_stmt(C)
				if not r then
					error("Cannot read statement in function body: " .. C[2])
				end
				table.insert(s, r)
			until false
			if not k or not (k.T == "i" or k.i == "end") then
				error("Function without end")
			end
			C[2] = C[2] + 1
			return { 4, a, s, span = { t.span[1], k.span[2] } }
		elseif keywords[t.i] then
			return
		else
			local p = ast_parse_path(C)
			local c = ast_parse_call(C, p)
			if c then
				return c
			end
			return p
		end
	elseif t.T == "l" then
		if t.t == "n" then
			C[2] = C[2] + 1
			return { 5, tonumber(t.i), span = t.span }
		elseif t.t == "'" or t.t == '"' or type(t.t) == "number" then
			C[2] = C[2] + 1
			return { 6, t.i, span = t.span }
		else
			error("Unknown literal at: " .. t.span[1] .. "-" .. t.span[2])
		end
	elseif t.T == "p" then
		if t.i == "{" then
			local T = ast_parse_table(C)
			if not T then
				error("Cannot parse table")
			end
			return T
		elseif t.i == "(" then
			C[2] = C[2] + 1
			tok_trim(C)
			local a = C[1][C[2]]
			if not a or (a.T == "p" and a.i == ")") then
				error("a group needs to have an expression inside it")
			end
			local e = ast_parse_expr(C)
			tok_trim(C)
			a = C[1][C[2]]
			if not a or a.T ~= "p" or a.i ~= ")" then
				error("A group needs to end!")
			end
			C[2] = C[2] + 1
			tok_trim(C)
			local S = C[2]
			local p = ast_parse_path_(C, S)
			if p then
				p[3] = e
				return p
			end
			C[2] = S
			return { 100, e, span = { t.span[1], e.span[2] } }
		end

		C[2] = C[2] + 1
		local ts = C[2]
		local s = C[1][C[2]]
		if s and s.T == "p" then
			if t.i == "." and s.i == "." then
				C[2] = C[2] + 1
				local l = C[1][C[2]]
				if l.T == "p" and l.i == "." then
					C[2] = C[2] + 1
					return { 101, span = { t.span[1], l.span[2] } }
				else
					C[2] = ts
				end
			else
			end
		end
		tok_trim(C)
		local r = ast_parse_expr(C)
		if t.i == "-" then
			if not r then
				error("Invalid `-` no right: " .. t.span[1] .. "-")
			end
			return { 50, r, span = { t.span[1], r.span[2] } }
		elseif t.i == "#" then
			if not r then
				error("Invalid `#` no right: " .. t.span[1] .. "-")
			end
			return { 51, r, span = { t.span[1], r.span[2] } }
		elseif t.i == "~" then
			if not r then
				error("Invalid `~` no right: " .. t.span[1] .. "-")
			end
			return { 52, r, span = { t.span[1], r.span[2] } }
		end
	end
end

ast_parse_expr = function(C)
	tok_trim(C)
	local l = ast_parse_expr_(C)
	if not l then
		return
	end
	l = ast_expr_apply_precedence(l)
	local S = C[2]
	tok_trim(C)
	local t = C[1][C[2]]
	if not t then
		return l
	end
	if t.T == "i" then
		if t.i == "and" then
			C[2] = C[2] + 1
			tok_trim(C)
			local r = ast_parse_expr(C)
			if not r then
				error("Invalid `and` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 11, l, r, span = { l.span[1], r.span[2] } })
		elseif t.i == "or" then
			C[2] = C[2] + 1
			tok_trim(C)
			local r = ast_parse_expr(C)
			if not r then
				error("Invalid `or` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 12, l, r, span = { l.span[1], r.span[2] } })
		else
			C[2] = S
			return l
		end
	elseif t.T == "p" then
		if t.i == "," or t.i == "}" or t.i == ";" or t.i == ")" then
			return l
		end

		if l[1] == 100 then
			local T = C[2]
			local c = ast_parse_call(C, { 200, {}, l })
			if c then
				return c
			end
			C[2] = T
		end

		C[2] = C[2] + 1
		local s = C[1][C[2]]

		if s and s.T == "p" then
			C[2] = C[2] + 1
			tok_trim(C)
			local r = ast_parse_expr(C)
			if t.i == "=" and s.i == "=" then
				if not r then
					error("Invalid `==` operation no, right at: " .. t.span[1] .. "-")
				end
				return ast_expr_apply_precedence({ 30, l, r, span = { l.span[1], r.span[2] } })
			elseif t.i == "~" and s.i == "=" then
				if not r then
					error("Invalid `~=` operation no, right at: " .. t.span[1] .. "-")
				end
				return ast_expr_apply_precedence({ 31, l, r, span = { l.span[1], r.span[2] } })
			elseif t.i == "<" and s.i == "=" then
				if not r then
					error("Invalid `<=` operation no, right at: " .. t.span[1] .. "-")
				end
				return ast_expr_apply_precedence({ 38, l, r, span = { l.span[1], r.span[2] } })
			elseif t.i == "." and s.i == "." then
				if not r then
					error("Invalid `..` operation no, right at: " .. t.span[1] .. "-")
				end
				return ast_expr_apply_precedence({ 32, l, r, span = { l.span[1], r.span[2] } })
			elseif t.i == ">" and s.i == "=" then
				if not r then
					error("Invalid `>=` operation no, right at: " .. t.span[1] .. "-")
				end
				return ast_expr_apply_precedence({ 39, l, r, span = { l.span[1], r.span[2] } })
			elseif t.i == "/" and s.i == "/" then
				if not r then
					error("Invalid `//` operation no, right at: " .. t.span[1] .. "-")
				end
				return ast_expr_apply_precedence({ 33, l, r, span = { l.span[1], r.span[2] } })
			elseif t.i == "<" and s.i == "<" then
				if not r then
					error("Invalid `<<` operation no, right at: " .. t.span[1] .. "-")
				end
				return ast_expr_apply_precedence({ 35, l, r, span = { l.span[1], r.span[2] } })
			elseif t.i == ">" and s.i == ">" then
				if not r then
					error("Invalid `>>` operation no, right at: " .. t.span[1] .. "-")
				end
				return ast_expr_apply_precedence({ 36, l, r, span = { l.span[1], r.span[2] } })
			end
		end

		tok_trim(C)

		local r = ast_parse_expr(C)
		if t.i == "+" then
			if not r then
				error("Invalid `+` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 20, l, r, span = { l.span[1], r.span[2] } })
		elseif t.i == "-" then
			if not r then
				error("Invalid `-` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 21, l, r, span = { l.span[1], r.span[2] } })
		elseif t.i == "*" then
			if not r then
				error("Invalid `*` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 22, l, r, span = { l.span[1], r.span[2] } })
		elseif t.i == "/" then
			if not r then
				error("Invalid `/` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 23, l, r, span = { l.span[1], r.span[2] } })
		elseif t.i == "^" then
			if not r then
				error("Invalid `^` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 24, l, r, span = { l.span[1], r.span[2] } })
		elseif t.i == "~" then
			if not r then
				error("Invalid `~` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 25, l, r, span = { l.span[1], r.span[2] } })
		elseif t.i == "&" then
			if not r then
				error("Invalid `&` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 26, l, r, span = { l.span[1], r.span[2] } })
		elseif t.i == "%" then
			if not r then
				error("Invalid `%` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 27, l, r, span = { l.span[1], r.span[2] } })
		elseif t.i == "<" then
			if not r then
				error("Invalid `<` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 28, l, r, span = { l.span[1], r.span[2] } })
		elseif t.i == ">" then
			if not r then
				error("Invalid `>` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 29, l, r, span = { l.span[1], r.span[2] } })
		elseif t.i == "|" then
			if not r then
				error("Invalid `|` expresion no, right at: " .. t.span[1] .. "-")
			end
			return ast_expr_apply_precedence({ 34, l, r, span = { l.span[1], r.span[2] } })
		end
	end
	C[2] = S
	return l
end

ast_parse_path_ = function(C, S)
	tok_trim(C)
	local s = C[1][C[2]]
	if s then
		if s.T == "i" then
			return
		elseif s.T == "p" then
			if s.i == "." then
				S = C[2]
				C[2] = C[2] + 1
				tok_trim(C)
				local l = ast_parse_path(C)
				if not l then
					C[2] = S
					return
				end
				return l
			elseif s.i == "[" then
				C[2] = C[2] + 1
				local e = ast_parse_expr(C)
				if not e then
					error("Cannot read path at: " .. S .. "-" .. s.span[2])
				end
				s = C[1][C[2]]
				if not s or s.T ~= "p" or s.i ~= "]" then
					error("path, path segment that starts with `[` is expected to end with `]`, at: " .. S .. "-" .. s.span[2])
				end
				C[2] = C[2] + 1
				local r = ast_parse_path_(C, S)
				if not r then
					return { 200, { e }, span = e.span }
				end
				table.insert(r[2], 1, e)
				return { 200, r[2], span = { e.span[1], r.span[2] } }
			elseif s.i == ";" then
				C[2] = C[2] + 1
			end
		end
	end
end
ast_parse_path = function(C)
	local t = C[1][C[2]]
	if not t or t.T ~= "i" or keywords[t.i] then
		return
	end

	C[2] = C[2] + 1
	local r = ast_parse_path_(C, t.span[1])
	if r then
		table.insert(r[2], 1, { 6, t.i, span = t.span })
		r.span[1] = t.span[1]
		return r
	end

	local o = { 200, { { 6, t.i, span = t.span } }, span = t.span }
	local S = C[2]
	local c = ast_parse_call(C, o)
	if c then
		local s = ast_parse_path_(C, C[2])
		if s then
			s[3] = c
			return s
		end
	end

	C[2] = S
	return o
end
ast_parse_table = function(C)
	local S = C[2]
	local a = C[1][C[2]]
	if a.T ~= "p" or a.i ~= "{" then
		return
	end

	local k, v, e = {}, {}, {}

	repeat
		C[2] = C[2] + 1
		tok_trim(C)
		a = C[1][C[2]]
		if not a then
			error("Cannot read table, EOF")
		end
		if a.T == "p" and a.i == "}" then
			break
		end
		local TS = C[2]
		local entry_added = false
		repeat
			local l
			if a.T == "p" and a.i == "[" then
				C[2] = C[2] + 1
				l = ast_parse_expr(C)
				if not l then
					error("Invalid expresion in table key, at: " .. C[2])
				end
				a = C[1][C[2]]
				if not a or a.T ~= "p" or a.i ~= "]" then
					error("Invalid table key, expected ]")
				end
			elseif a.T == "i" then
				if keywords[a.i] then
					break
				end
				l = { 6, a.i, span = a.span }
			else
				break
			end
			C[2] = C[2] + 1
			tok_trim(C)
			a = C[1][C[2]]
			if not a or a.T ~= "p" or a.i ~= "=" then
				break
			end
			C[2] = C[2] + 1
			tok_trim(C)
			local r = ast_parse_expr(C)
			if not r then
				error("table, cannot parse value, at: " .. C[2])
			end
			table.insert(k, l)
			table.insert(v, r)
			tok_trim(C)
			a = C[1][C[2]]
			entry_added = true
		until true
		if not entry_added then
			C[2] = TS
			a = C[1][C[2]]
			local l = ast_parse_expr(C)
			if not l then
				error("table, cannot parse element, at: " .. C[2])
			end
			tok_trim(C)
			a = C[1][C[2]]
			table.insert(e, l)
		end
	until not a or not (a.T == "p" and a.i == ",")
	if not a or a.T ~= "p" or a.i ~= "}" then
		error("table, unexpected table end")
	end
	C[2] = C[2] + 1

	for i, o in ipairs(e) do
		table.insert(k, { 5, i })
		table.insert(v, o)
	end

	return { 7, k, v, span = { S, a.span[2] } }
end

local function ast_parse_call_(C, p)
	local S, E = C[2], 0
	local a = C[1][C[2]]
	if not a then
		return
	end
	local P = {}
	if a.T == "p" and a.i == "(" then
		local e = nil
		C[2] = C[2] + 1
		tok_trim(C)
		a = C[1][C[2]]
		while a and not (a.T == "p" and a.i == ")") do
			e = ast_parse_expr(C)
			if e then
				table.insert(P, e)
			end
			tok_trim(C)
			a = C[1][C[2]]
			if a.T == "p" and a.i == "," then
				C[2] = C[2] + 1
				tok_trim(C)
			end
		end
		if not a or a.T ~= "p" or a.i ~= ")" then
			error("Unclosed call")
		end
		E = a.span[2]
		C[2] = C[2] + 1
		return { 10, p, P, span = { S, E } }
	elseif a.T == "p" and a.i == "{" then
		local t = ast_parse_table(C)
		if not t then
			error("Cannot parse table")
		end
		table.insert(P, t)
		return { 10, p, P, span = { S, t.span[2] } }
	elseif a.T == "l" and (a.t == "'" or a.t == '"' or type(a.t) == "number") then
		C[2] = C[2] + 1
		table.insert(P, { 6, a.i, span = a.span })
		return { 10, p, P, span = { S, E } }
	end
end

ast_parse_call = function(C, p)
	local a = C[1][C[2]]
	if a and a.T == "p" and a.i == ":" then
		C[2] = C[2] + 1
		tok_trim(C)
		a = C[1][C[2]]
		if not a or a.T ~= "i" then
			error("Invalid call with :")
		end
		C[2] = C[2] + 1
		local r = ast_parse_call_(C, p)
		return { 9, p, a, r[3], span = { a.span[1], r.span[2] } }
	else
		local S = C[2]
		local r = ast_parse_call_(C, p)
		if not r then
			C[2] = S
			return
		end
		local s = C[2]
		local t = ast_parse_path_(C, s)
		if not t then
			s = C[2]
			t = ast_parse_call(C, { 200, {}, r })
			if t then
				return t
			end
			C[2] = s
			return r
		end
		S = C[2]
		t[3] = r
		tok_trim(C)
		t = ast_parse_call(C, t)
		if not t then
			C[2] = s
			return r
		end

		C[2] = s
		return g
	end
end

local parse_function = function(C, is_local)
	local t, k = C[1][C[2]], nil
	if not t or t.T ~= "i" or t.i ~= "function" then
		error("parse_function was called when there is not function!")
	end

	C[2] = C[2] + 1
	tok_trim(C)
	local a = {}
	local P
	if is_local then
		t = C[1][C[2]]
		if not t or t.T ~= "i" then
			error("Expect <ident> after `local function `")
		end

		if keywords[t.i] then
			error("keyward used as the function name for `local function`: " .. t.i)
		end

		P = t.i
		C[2] = C[2] + 1
	else
		P = ast_parse_path(C)
		if not P then
			error("Cannot read function definition path")
		end
		tok_trim(C)
		local k = C[1][C[2]]
		if k.T == "p" then
			if k.i == ":" then
				C[2] = C[2] + 1
				tok_trim(C)
				k = C[1][C[2]]
				if k.T ~= "i" then
					error("expect function name, ident")
				end

				if keywords[k.i] then
					error("recerved keyword used as function name")
				end
				table.insert(a, "self")
				table.insert(P[2], { 6, k.i, span = k.span })

				C[2] = C[2] + 1
			end
		end
	end

	tok_trim(C)
	k = C[1][C[2]]
	if not k or not (k.T == "p" and k.i == "(") then
		error("Function definition expects the paramenters to begin wtih `(`")
	end
	repeat
		C[2] = C[2] + 1
		tok_trim(C)
		k = C[1][C[2]]
		if k and k.T == "p" and k.i == ")" then
			break
		end
		if not k or not k.T == "i" then
			error("Expecting an ident for the function paramenters")
		end
		table.insert(a, k.i)
		C[2] = C[2] + 1
		tok_trim(C)
		k = C[1][C[2]]
		if k.T == "p" and k.i == ")" then
		elseif not (k.T == "p" and k.i == ",") then
			error("No `,` between parameters, `,` is required to separate aparameters")
		end
	until not k or (k.T == "p" and k.i == ")")
	if not k or not (k.T == "p" and k.i == ")") then
		error("Cannot find function parameters end, `)`")
	end

	C[2] = C[2] + 1

	local s = {}
	repeat
		tok_trim(C)
		k = C[1][C[2]]
		while k and k.T == "p" and k.i == ";" do
			C[2] = C[2] + 1
			tok_trim(C)
			k = C[1][C[2]]
		end
		if not k or k.T == "i" and k.i == "end" then
			break
		end
		local r = ast_parse_stmt(C)
		if not r then
			error("Cannot read statement in function body")
		end
		table.insert(s, r)
	until false
	if not k or not (k.T == "i" or k.i == "end") then
		error("Function without end")
	end
	C[2] = C[2] + 1

	return { 306, is_local, P, a, s }
end

ast_parse_stmt = function(C)
	tok_trim(C)
	local t = C[1][C[2]]
	while t and t.T == "p" and t.i == ";" do
		C[2] = C[2] + 1
		tok_trim(C)
		t = C[1][C[2]]
	end
	if not t then
		return
	end
	if t.T == "i" then
		if t.i == "local" then
			local S, E = t.span[1], t.span[2]
			local D = {}
			C[2] = C[2] + 1
			tok_trim(C)
			local a = C[1][C[2]]
			if not a or a.T ~= "i" then
				error("local, expects <ident> or function after `local`")
			end

			if a.i == "function" then
				return parse_function(C, true)
			end

			if keywords[a.i] then
				error("local, using reserved keyword: `" .. a.i .. "` for the first local <ident>, is invalid")
			end
			table.insert(D, a.i)

			E = C[2]
			C[2] = C[2] + 1
			tok_trim(C)
			a = C[1][C[2]]

			if not a or a.T ~= "p" or not (a.i == "," or a.i == "=") then
				return { 300, D, span = { S, E } }
			end

			while a and a.T == "p" and a.i == "," do
				C[2] = C[2] + 1
				tok_trim(C)
				a = C[1][C[2]]
				if not a or a.T ~= "i" or keywords[a.i] then
					return { 300, D, span = { S, E } }
				end
				E = C[2]
				table.insert(D, a.i)
				C[2] = C[2] + 1
				tok_trim(C)
				a = C[1][C[2]]
			end

			if not a or a.T ~= "p" then
				return { 300, D, span = { S, E } }
			end

			if a.i == ";" then
				E = C[2]
				C[2] = C[2] + 1
				return { 300, D, span = { S, E } }
			end

			if a.i ~= "=" then
				error("local, after [<ident>] an `=` is expected")
			end

			local e = {}
			repeat
				C[2] = C[2] + 1
				local l = ast_parse_expr(C)
				if not l then
					break
				end
				table.insert(e, l)
				E = l.span[2]
				tok_trim(C)
				a = C[1][C[2]]
				if (not a) or not (a.T == "p" and a.i == ",") then
					break
				end
			until not a or (a.T == "i" and keywords[a.i]) or (a.T == "p" and a.i == ";")
			return { 300, D, e, span = { S, E } }
		elseif t.i == "do" then
			local s = {}
			local a
			C[2] = C[2] + 1
			tok_trim(C)
			repeat
				a = C[1][C[2]]
				while a and a.T == "p" and a.i == ";" do
					C[2] = C[2] + 1
					tok_trim(C)
					a = C[1][C[2]]
				end
				if not a or (a.T == "i" and a.i == "end") then
					break
				end
				local l = ast_parse_stmt(C)
				tok_trim(C)
				if not l then
					error("Cannot read statement from within do block")
				end
				table.insert(s, l)
			until not a or (a.T == "i" and a.i == "end")

			if not a or a.T ~= "i" or a.i ~= "end" then
				error("Cannot find the end on a `do`")
			end

			return { 301, s, span = { t.span[1], a.span[2] } }
		elseif t.i == "if" then
			C[2] = C[2] + 1
			tok_trim(C)
			local c, s, b, a, l, r = {}, {}, {}, nil, nil, nil
			l = ast_parse_expr(C)
			if not l then
				error("Cannot read if condition")
			end
			table.insert(c, l)

			tok_trim(C)
			a = C[1][C[2]]
			if not a or a.T ~= "i" or a.i ~= "then" then
				error("Expecting `then` after if condition")
			end
			C[2] = C[2] + 1
			tok_trim(C)

			local has_else = false
			while a and not (a.T == "i" and a.i == "end") do
				repeat
					a = C[1][C[2]]
					if not a then
						error("Unexpected if: End Of Stream")
					end

					if a.T == "i" then
						if a.i == "end" then
							table.insert(s, b)
							b = {}
							break
						elseif a.i == "else" then
							table.insert(s, b)
							b = {}
							C[2] = C[2] + 1
							tok_trim(C)
							has_else = true
							break
						elseif a.i == "elseif" then
							if has_else then
								error("Already has else, an elseif cannot be after else")
							end

							table.insert(s, b)
							b = {}
							C[2] = C[2] + 1
							tok_trim(C)
							l = ast_parse_expr(C)
							if not l then
								error("Expect expresion after elseif")
							end
							table.insert(c, l)
							tok_trim(C)
							a = C[1][C[2]]
							if not a or a.T ~= "i" or a.i ~= "then" then
								error("Expect then after elseif <expr>")
							end
							C[2] = C[2] + 1
							tok_trim(C)
							break
						end
					end
					r = ast_parse_stmt(C)
					if not r then
						error("Cannot parse statement in if block")
					end
					table.insert(b, r)
					tok_trim(C)
				until true
			end
			if not a or a.T ~= "i" or a.i ~= "end" then
				error("Expecting end for the if statements")
			end
			C[2] = C[2] + 1

			return { 302, c, s }
		elseif t.i == "while" then
			C[2] = C[2] + 1
			tok_trim(C)
			local b, c, a, s = {}, nil, nil, nil
			c = ast_parse_expr(C)
			if not c then
				error("Expect while condition")
			end
			tok_trim(C)
			a = C[1][C[2]]
			if not a or a.T ~= "i" or a.i ~= "do" then
				error("Expect do after while condition")
			end
			C[2] = C[2] + 1
			tok_trim(C)
			a = C[1][C[2]]
			while a and not (a.T == "i" and a.i == "end") do
				s = ast_parse_stmt(C)
				if not s then
					error("Cannot read statement")
				end
				table.insert(b, s)
				tok_trim(C)
				a = C[1][C[2]]
			end
			if not a or a.T ~= "i" or a.i ~= "end" then
				error("a while is expected to be ended in a while")
			end
			C[2] = C[2] + 1

			return { 303, c, b }
		elseif t.i == "for" then
			C[2] = C[2] + 1
			tok_trim(C)

			local n = C[1][C[2]]
			if not n or n.T ~= "i" then
				error("after for an <ident> is expected")
			end

			if keywords[n.i] then
				error("for, reservd name used: " .. n.i)
			end
			C[2] = C[2] + 1
			tok_trim(C)

			local a = C[1][C[2]]
			if not a or a.T ~= "p" then
				error("for, after parameter is expected `,` or `=`")
			end

			if a.i == "=" then
				C[2] = C[2] + 1
				tok_trim(C)

				local s = ast_parse_expr(C)
				if not s then
					error("for, expect initial value of " .. n.i .. "as expresion")
				end
				tok_trim(C)
				a = C[1][C[2]]
				if not a or a.T ~= "p" then
					error("for " .. n.i .. "=<expr>" .. "expects `,`")
				end
				C[2] = C[2] + 1
				tok_trim(C)
				local m = ast_parse_expr(C)
				if not m then
					error("for " .. n.i .. "=<expr>,<expr> as needs limit")
				end
				local i
				tok_trim(C)
				a = C[1][C[2]]
				if not a then
					error("expect `do` or `,`")
				end

				if a.T == "p" and a.i == "," then
					C[2] = C[2] + 1
					tok_trim(C)
					i = ast_parse_expr(C)
					tok_trim(C)
					a = C[1][C[2]]
				else
					i = { 5, 1 }
				end

				if a.T ~= "i" or a.i ~= "do" then
					error("expect do")
				end

				C[2] = C[2] + 1
				tok_trim(C)

				local b, l = {}, nil
				a = C[1][C[2]]
				while a and not (a.T == "i" and a.i == "end") do
					l = ast_parse_stmt(C)
					if not l then
						error("for, cannot read statement")
					end
					table.insert(b, l)
					tok_trim(C)
					a = C[1][C[2]]
				end
				if a.T ~= "i" or a.i ~= "end" then
					error("for, cannot found end")
				end
				C[2] = C[2] + 1

				return { 304, n.i, s, m, i, b }
			end

			local k = { n.i }
			while a and (a.T == "p" and a.i == ",") do
				C[2] = C[2] + 1
				tok_trim(C)
				a = C[1][C[2]]
				if not a or a.T ~= "i" then
					error("Expected <ident> for `for` parameter name")
				end
				if keywords[a.i] then
					error("reserved keyword used as paremeter name in for")
				end
				table.insert(k, a.i)
				C[2] = C[2] + 1
				tok_trim(C)
				a = C[1][C[2]]
			end

			if not a or a.T ~= "i" or a.i ~= "in" then
				error("after for parameters, an `in` is expected!")
			end
			C[2] = C[2] + 1
			tok_trim(C)
			local e = ast_parse_expr(C)
			if not e then
				error("for, after `in` is expected an expression!")
			end
			tok_trim(C)
			a = C[1][C[2]]
			if a.T ~= "i" or a.i ~= "do" then
				error("after for expression, `do` is expected!")
			end
			C[2] = C[2] + 1
			tok_trim(C)
			a = C[1][C[2]]

			local b, l = {}, nil
			while a and not (a.T == "i" and a.i == "end") do
				l = ast_parse_stmt(C)
				if not l then
					error("for, cannot read statement!")
				end
				table.insert(b, l)
				tok_trim(C)
				a = C[1][C[2]]
			end

			if not a or a.T ~= "i" or a.i ~= "end" then
				error("for, cannot find end")
			end
			C[2] = C[2] + 1

			return { 309, k, e, b }
		elseif t.i == "repeat" then
			C[2] = C[2] + 1
			tok_trim(C)
			local b, a, e, l = {}, nil, nil, nil
			a = C[1][C[2]]
			while a and not (a.T == "i" and a.i == "until") do
				l = ast_parse_stmt(C)
				if not l then
					error("repeat, cannot read statement")
				end
				table.insert(b, l)
				tok_trim(C)
				a = C[1][C[2]]
			end
			if not a or a.T ~= "i" or a.i ~= "until" then
				error("repeat, is expected to end with until")
			end
			C[2] = C[2] + 1
			tok_trim(C)
			e = ast_parse_expr(C)
			if not e then
				error("repeat, cannot read until expression")
			end

			return { 305, e, b }
		elseif t.i == "break" then
			C[2] = C[2] + 1
			return { 308, span = t.span }
		elseif t.i == "return" then
			local e = {}
			local a
			repeat
				C[2] = C[2] + 1
				local l = ast_parse_expr(C)
				if not l then
					break
				end
				table.insert(e, l)
				E = l.span[2]
				tok_trim(C)
				a = C[1][C[2]]
				if (not a) or not (a.T == "p" and a.i == ",") then
					break
				end
			until not a or (a.T == "i" and keywords[a.i]) or (a.T == "p" and a.i == ";")
			if not a then
				a = t
			end
			return { 307, e, span = { t.span[1], a.span[2] } }
		elseif t.i == "function" then
			return parse_function(C, false)
		else
			local S, E = t.span[1], t.span[2]
			local L = {}
			local a
			repeat
				tok_trim(C)
				local p = ast_parse_path(C)
				if p then
					table.insert(L, p)
				end
				tok_trim(C)
				a = C[1][C[2]]
				if a then
					E = a.span[2]
					local c = ast_parse_call(C, p)
					if c then
						return c
					end
					if a.T == "p" and a.i ~= "," then
						break
					end
					C[2] = C[2] + 1
				end
			until not a or (a.T == "i" and keywords[a.i]) or (a.T == "p" and a.i == "=")

			if a and a.T == "p" and a.i == "=" then
				local R = {}
				repeat
					C[2] = C[2] + 1
					local l = ast_parse_expr(C)
					if not l then
						break
					end
					table.insert(R, l)
					E = l.span[2]
					tok_trim(C)
					a = C[1][C[2]]
				until not a or (a.T == "i" and keywords[a.i]) or a.T ~= "p" or a.i ~= ","

				return { 310, L, R, span = { t.span[1], R[#R].span[2] } }
			end
		end
	end
end

local function ast_parse_module(tokens)
	local C = { tokens, 1 }
	local b = {}
	tok_trim(C)
	while C[2] <= #C[1] do
		local stmt = ast_parse_stmt(C)
		tok_trim(C)
		if not stmt then
			error("Cannot read statement!")
		end
		table.insert(b, stmt)
	end

	return { 4, {}, b }
end

local function compile(n, _C)
	local C = _C or {}

	if n[1] == 5 or n[1] == 6 then
		return { 7, n[2] }
	elseif n[1] == 0 then -- nil
		return { 7 }
	elseif n[1] == 1 then -- false
		return { 7, false }
	elseif n[1] == 2 then -- true
		return { 7, true }
	elseif n[1] == 3 then -- not
		return { 17, compile(n[2], C) }
	elseif n[1] == 4 then -- function
		local S = {}
		local TC = {}
		for _, a in ipairs(n[3]) do
			local r = compile(a, TC)
			if TC.before then
				for _, o in ipairs(TC.before) do
					table.insert(S, o)
				end
				TC.before = nil
			end
			table.insert(S, r)
		end

		return { 6, n[2], S }
	elseif n[1] == 7 then -- table
		local k, v = {}, {}
		for _, a in ipairs(n[2]) do
			table.insert(k, compile(a, C))
		end
		for _, a in ipairs(n[3]) do
			table.insert(v, compile(a, C))
		end
		return { 3, k, v }
	elseif n[1] == 9 then -- call self
		local p = compile(n[2], C)
		local i = (C.r or 0) + 1
		C.r = i
		C.before = C.before or {}
		table.insert(C.before, { 2, { { { i }, 0 } }, { p } })
		local A = { { 4, { { { i }, 0 } } } }
		for _, a in ipairs(n[4]) do
			table.insert(A, compile(a, C))
		end
		return { 8, { 4, { { { i, n[3].i }, 0 } } }, A }
	elseif n[1] == 10 then -- call
		local P = compile(n[2], C)
		local A = {}
		for _, a in ipairs(n[3]) do
			table.insert(A, compile(a, C))
		end
		return { 8, P, A }
	elseif n[1] == 11 then -- and
		return { 40, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 12 then -- or
		return { 39, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 20 then -- add
		return { 18, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 21 then -- sub
		return { 19, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 22 then -- mul
		return { 20, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 23 then -- div
		return { 21, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 24 then -- pow
		return { 22, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 25 then -- `~` xor
		return { 26, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 26 then -- `&` bit and
		return { 25, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 27 then -- `%` modulo
		return { 27, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 28 then -- `<`
		return { 37, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 29 then -- `>`
		return { 33, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 30 then -- equals
		return { 35, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 31 then -- not equals
		return { 38, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 32 then -- concat
		return { 23, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 33 then -- //
		return { 41, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 34 then -- |
		return { 24, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 35 then -- <<
		return { 31, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 36 then -- <<
		return { 32, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 38 then -- <=
		return { 36, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 39 then -- >=
		return { 34, compile(n[2], C), compile(n[3], C) }
	elseif n[1] == 50 then -- negative
		return { 28, compile(n[2], C) }
	elseif n[1] == 51 then -- length
		return { 30, compile(n[2], C) }
	elseif n[1] == 52 then -- negate
		return { 29, compile(n[2], C) }
	elseif n[1] == 100 then -- group
		local i = (C.r or 0) + 1
		C.r = i

		C.before = C.before or {}
		table.insert(C.before, { 2, { { { i }, 0 } }, { compile(n[2], C) } })
		return { 4, { { { i }, 0 } } }
	elseif n[1] == 101 then -- variadic
		return { 5 }
	elseif n[1] == 200 then -- path
		local P = {}
		local base = nil
		if n[3] then
			base = compile(n[3], C)
		end
		for _, a in ipairs(n[2]) do
			table.insert(P, compile(a, C))
		end
		return { 4, { { P, base } } }
	elseif n[1] == 300 then -- local
		if not n[3] then
			return { 1, n[2] }
		end

		local e = {}
		for _, a in ipairs(n[3]) do
			table.insert(e, compile(a, C))
		end

		local p = {}
		for _, a in ipairs(n[2]) do
			table.insert(p, { { a } })
		end
		C.before = C.before or {}
		table.insert(C.before, { 1, n[2] })

		return { 2, p, e }
	elseif n[1] == 301 then -- do
		local E = {}
		for _, a in ipairs(n[2]) do
			local r = compile(a, C)
			if C.before then
				for _, o in ipairs(C.before) do
					table.insert(E, o)
				end
				C.before = nil
			end
			table.insert(E, r)
		end
		return { 14, E }
	elseif n[1] == 302 then -- if
		local c, s, t = {}, {}, {}
		for _, a in ipairs(n[2]) do
			table.insert(c, compile(a, C))
		end
		for _, a in ipairs(n[3]) do
			local TC = {}
			for _, l in ipairs(a) do
				local r = compile(l, TC)
				if TC.before then
					for _, o in ipairs(TC.before) do
						table.insert(t, o)
					end
				end
				table.insert(t, r)
			end

			table.insert(s, { 14, t })
			t = {}
		end
		local r, T = { 7 }, nil
		t = r
		for i = 1, #c, 1 do
			t = { 9, c[i], s[i], { 7 } }
			if T then
				T[4] = t
			else
				r = t
			end
			T = t
		end
		if #c < #s then
			T[4] = s[#s]
		end

		return r
	elseif n[1] == 303 then -- While
		local CC, c = {}, {}
		local tc = compile(n[2], CC)
		if CC.before then
			for _, o in ipairs(CC.before) do
				table.insert(c, o)
			end
		end
		table.insert(c, tc)

		c = { 8, { 6, {}, c }, {} }

		local TC = {}
		local b = {}
		for _, a in ipairs(n[3]) do
			local r = compile(a, TC)
			if TC.before then
				for _, o in ipairs(TC.before) do
					table.insert(b, o)
				end
				TC.before = nil
			end
			table.insert(b, r)
		end
		return { 10, c, b }
	elseif n[1] == 304 then -- for
		local TC = {}

		local s = compile(n[3], C)
		local e = compile(n[4], C)
		local i = compile(n[5], C)
		local b = {}
		for _, l in ipairs(n[6]) do
			local r = compile(l, TC)
			if TC.before then
				for _, o in ipairs(TC.before) do
					table.insert(b, o)
				end
				TC.before = nil
			end
			table.insert(b, r)
		end

		return { 11, s, e, i, n[2], b }
	elseif n[1] == 305 then -- repeat
		local TC, b = {}, {}
		for _, s in ipairs(n[3]) do
			local r = compile(s, TC)
			if TC.before then
				for _, o in ipairs(TC.before) do
					table.insert(b, o)
				end
				TC.before = nil
			end
			table.insert(b, r)
		end
		local e = compile(n[2], TC)
		if TC.before then
			for _, o in ipairs(TC.before) do
				table.insert(b, o)
			end
			TC.before = nil
		end

		return { 13, e, b }
	elseif n[1] == 306 then -- d function
		local S = {}
		local TC = {}
		for _, a in ipairs(n[5]) do
			local r = compile(a, TC)
			if TC.before then
				for _, o in ipairs(TC.before) do
					table.insert(S, o)
				end
				TC.before = nil
			end
			table.insert(S, r)
		end
		if n[2] then
			table.insert(C, { 1, { n[3] } })
			return { 2, { { { n[3] } } }, { { 6, n[4], S } } }
		end

		return { 2, { compile(n[3], C)[2][1] }, { { 6, n[4], S } } }
	elseif n[1] == 307 then -- return
		local e = {}
		for _, a in ipairs(n[2]) do
			table.insert(e, compile(a, C))
		end
		return { 15, e }
	elseif n[1] == 308 then -- break
		return { 16 }
	elseif n[1] == 309 then -- foreach
		local TC, b, r = {}, {}, nil
		local e = compile(n[3], C)
		for _, s in ipairs(n[4]) do
			r = compile(s, TC)
			if TC.before then
				for _, o in ipairs(TC.before) do
					table.insert(b, o)
				end
				TC.before = nil
			end
			table.insert(b, r)
		end
		return { 12, e, n[2], b }
	elseif n[1] == 310 then -- set
		local P = {}
		local A = {}
		for _, a in ipairs(n[2]) do
			table.insert(P, compile(a, C)[2][1])
		end
		for _, a in ipairs(n[3]) do
			table.insert(A, compile(a, C))
		end
		return { 2, P, A }
	else
		print(n[1])
		error("TODO")
	end
end

return {
	parse = parse,
	ast_parse_expr = function(tokens)
		return ast_parse_expr({ tokens, 1 })
	end,
	ast_parse_module = ast_parse_module,
	ast_parse_stmt = function(tokens)
		return ast_parse_stmt({ tokens, 1 })
	end,
	compile = compile,
	compile_to_function = function(ast_node)
		local TC = {}
		local bytecode = {}
		local r = compile(ast_node, TC)
		if TC.before then
			for _, o in ipairs(TC.before) do
				table.insert(bytecode, o)
			end
		end
		table.insert(bytecode, r)
		return { 6, {}, bytecode }
	end,
}
