local frontend = require("frontend-lua")
local executor = require("executor")

local function show_table(table, depth)
	depth = depth or 0
	if type(table) == "table" then
		local out = "{\n"
		for i, v in pairs(table) do
			if tonumber(i) then
				out = out .. string.format("%s[%s] = %s,\n", string.rep("    ", depth + 1), i, show_table(v, depth + 1))
			else
				out = out
					.. string.format('%s["%s"] = %s,\n', string.rep("    ", depth + 1), i, show_table(v, depth + 1))
			end
		end
		return out .. string.rep("    ", depth) .. "}"
	elseif type(table) == "string" then
		return string.format('"%s"', table)
	else
		return string.format("%s", table)
	end
end

local tests = {}

-- Initialy generated by Gemini 3 Fast
--
-- Comprehensive Test Suite for Lua Operations
-- Categories: Arithmetic, Bitwise, Comparison, Logic, and String/Table

-- 1. ARITHMETIC OPERATIONS
table.insert(tests, {
	"addition",
	"10 + 11",
	21, -- Basic integer addition
})

table.insert(tests, {
	"subtraction",
	"50 - 25",
	25,
})

table.insert(tests, {
	"multiplication",
	"6 * 7",
	42,
})

table.insert(tests, {
	"float_division",
	"5 / 2",
	2.5, -- Lua 5.3+ always returns float for /
})

table.insert(tests, {
	"floor_division",
	"5 // 2",
	2, -- Returns the floor of the quotient
})

table.insert(tests, {
	"modulo",
	"10 % 3",
	1,
})

table.insert(tests, {
	"exponentiation",
	"2 ^ 3",
	8.0, -- Always returns a float
})

table.insert(tests, {
	"unary_minus",
	"-(-10)",
	10,
})

-- 2. BITWISE OPERATIONS (Lua 5.3+)
table.insert(tests, {
	"bitwise_and",
	"6 & 3", -- binary: 110 & 011 = 010
	2,
})

table.insert(tests, {
	"bitwise_or",
	"4 | 2", -- binary: 100 | 010 = 110
	6,
})

table.insert(tests, {
	"bitwise_xor",
	"7 ~ 3", -- binary: 111 ~ 011 = 100
	4,
})

table.insert(tests, {
	"bitwise_not",
	"~0", -- Result depends on bit width (usually -1 in 2's complement)
	-1,
})

table.insert(tests, {
	"left_shift",
	"1 << 3", -- 1 shifted left by 3 is 2^3
	8,
})

table.insert(tests, {
	"right_shift",
	"16 >> 2",
	4,
})

-- 3. COMPARISON AND LOGICAL OPS
table.insert(tests, {
	"equality",
	"10 == 10",
	true,
})

table.insert(tests, {
	"inequality",
	"5 ~= 10",
	true,
})

table.insert(tests, {
	"less_than",
	"5 < 10",
	true,
})

table.insert(tests, {
	"logical_and",
	"true and 5", -- Returns the second operand if first is truthy
	5,
})

table.insert(tests, {
	"logical_or",
	"false or 'default'", -- Returns the second operand if first is falsy
	"default",
})

table.insert(tests, {
	"logical_not",
	"not (1 == 1)",
	false,
})

-- 4. STRING AND TABLE FEATURES
table.insert(tests, {
	"concatenation",
	"'Lua' .. ' 5.5'",
	"Lua 5.5",
})

table.insert(tests, {
	"length_operator_table",
	"#{10, 20, 30}",
	3,
})

table.insert(tests, {
	"length_operator_string",
	"#'hello'",
	5,
})

-- Precedence and Associativity Tests
-- Format: "Name", "Source", Result

-- 1. Arithmetic Precedence (Multiplication over Addition)
table.insert(tests, { "mul_precedence", "5 + 2 * 10", 25 })

-- 2. Power Precedence (Power over Unary Minus)
-- Note: -2^2 in Lua is -(2^2) = -4.0
table.insert(tests, { "power_precedence", "-2 ^ 2", -4.0 })

-- 3. Power Associativity (Right-to-Left)
-- 2^2^3 is 2^(2^3) = 2^8 = 256
table.insert(tests, { "power_associativity", "2 ^ 2 ^ 3", 256.0 })

-- 4. Unary and Binary Precedence
table.insert(tests, { "unary_precedence", "-5 + 10", 5 })

-- 5. Concatenation Associativity (Right-to-Left)
table.insert(tests, { "concat_associativity", "'a' .. 'b' .. 'c'", "abc" })

-- 6. Bitwise vs Arithmetic (Arithmetic is higher)
-- 1 << 2 + 1 is 1 << (2 + 1) = 1 << 3 = 8
table.insert(tests, { "bitwise_arith_precedence", "1 << 2 + 1", 8 })

-- 7. Comparison vs Logical
-- 10 == 10 and 5 > 2 is (10 == 10) and (5 > 2) = true
table.insert(tests, { "logical_comp_precedence", "10 == 10 and 5 > 2", true })

-- 8. Complex Logical Precedence (AND over OR)
-- false and true or true is (false and true) or true = true
table.insert(tests, { "and_or_precedence", "false and true or true", true })

-- 9. Parentheses Overriding Precedence
table.insert(tests, { "parentheses_override", "(5 + 2) * 10", 70 })

-- 10. Modulo and Floor Division (Same level as Mul/Div, Left-to-Right)
-- 10 % 3 // 2 is (10 % 3) // 2 = 1 // 2 = 0
table.insert(tests, { "modulo_floor_precedence", "10 % 3 // 2", 0 })

table.insert(tests, {
	"IIFE",
	[=[(function() return 21 end)()]=],
	21,
})

table.insert(tests, {
	"IIFE, local",
	[=[
	(function()
		local a = 32
		return a
	end)()
	]=],
	32,
})

table.insert(tests, {
	"IIFE, set",
	[=[
	(function()
		local a = 32
		a = 138
		return a
	end)()
	]=],
	138,
})

table.insert(tests, {
	"IIFE, if true",
	[=[
	(function()
		if true then
			return 10
		end
		return 21
	end)()
	]=],
	10,
})

table.insert(tests, {
	"IIFE, if false",
	[=[
	(function()
		if false then
			return 10
		else
			return 100
		end
		return 21
	end)()
	]=],
	100,
})

table.insert(tests, {
	"IIFE, if elseif",
	[=[
	(function()
		if false then
			return 10
		elseif true then
			return 323
		else
			return 100
		end
		return 21
	end)()
	]=],
	323,
})

table.insert(tests, {
	"IIFE, while",
	[=[
	(function()
		local a = 0
		while a < 10 do
			a = a + 1
		end
		return a
	end)()
	]=],
	10,
})

table.insert(tests, {
	"IIFE, while break",
	[=[
	(function()
		local a = 0
		while a < 100 do
			a = a + 1
			if a == 50 then break end
		end
		return a
	end)()
	]=],
	50,
})

table.insert(tests, {
	"IIFE, return multires",
	[=[
	(function()
		local f = function()
			return 200, 150
		end
		local a, b = f()
		return a + b
	end)()
	]=],
	350,
})

table.insert(tests, {
	"IIFE, for a=1,21,1",
	[=[
	(function()
		local sum, last = 0
		for a=1,21,1 do
			sum = sum + a
			last = a
		end
		return sum * last
	end)()
	]=],
	4851,
})

table.insert(tests, {
	"IIFE, for k,v in {10, 20, 30}",
	[=[
	(function()
		local sum, sumk = 0, 0
		for k,v in ipairs({10, 20, 30}) do
			sumk = sumk + k
			sum = sum + v
		end
		return sum * sumk
	end)()
	]=],
	360,
})

local function run_test(test)
	local name, source, result = table.unpack(test)
	local is_ok, tokens_or_error, ast_node_or_error, bytecode_or_error, res
	is_ok, tokens_or_error = pcall(frontend.parse, source)
	if not is_ok then
		print("\tError while parsing")
		print("\t" .. tokens_or_error)
		return false
	end
	is_ok, ast_node_or_error = pcall(frontend.ast_parse_expr, tokens_or_error)
	if not is_ok then
		print("Tokens:", show_table(tokens_or_error))
		print("\tError while parsing expression")
		print("\t" .. ast_node_or_error)
		return false
	end

	local C, bytecode = {}, {}

	is_ok, bytecode_or_error = pcall(frontend.compile, ast_node_or_error, C)
	if not is_ok then
		print("AST:", show_table(ast_node_or_error))
		print("\tError while compiling ast_node")
		print("\t" .. bytecode_or_error)
		return false
	end
	if C.before then
		for _, o in ipairs(C.before) do
			table.insert(bytecode, o)
		end
	end
	for _, o in ipairs(bytecode_or_error) do
		table.insert(bytecode, o)
	end

	local context = { ipairs = ipairs }
	is_ok, res = pcall(executor.execute, context, { 6, {}, bytecode })
	if not is_ok then
		print("AST:", show_table(ast_node_or_error))
		print("Bytecode:", show_table(bytecode))
		print("\tError while executing")
		print("\t" .. res)
		return false
	end

	is_ok, res = pcall(res)
	if not is_ok then
		print("AST:", show_table(ast_node_or_error))
		print("Bytecode:", show_table(bytecode))
		print("\tError while running the virtual function")
		print("\t" .. res)
		return false
	end

	if result == res then
		return true
	end

	print("AST:", show_table(ast_node_or_error))
	print("Bytecode:", show_table(bytecode))
	print("\t Not maching: " .. show_table(result) .. " ~= " .. show_table(res))
	return false
end

local passed = 0
for _, test in ipairs(tests) do
	print(test[1] .. ":")
	if run_test(test) then
		passed = passed + 1
	else
		print("Failed")
	end
end

print()
print("Results: " .. passed .. "/" .. #tests)
